### Import Neccessary Libraries

In [1]:
import torch
from torch import nn

### Data generation


In [2]:
# Create *known* parameters    
weight = 0.7
bias = 0.3

# Create
start = 0
end = 1 
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1)
y =  weight  * X + bias

X[:10], y[:10] 

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

### Data splitting 

In [3]:
split = int(0.8 * len(X))

X_train, y_train = X[:split], y[:split]
X_test, y_test = X[split:], y[split:]



### Model Building


In [4]:
class PracticeModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer_1 = nn.Linear(in_features= 1, out_features=10)
        self.layer_2 = nn.Linear(in_features= 10, out_features=10)
        self.layer_3 = nn.Linear(in_features= 10, out_features= 1)

    def forward(self, x):
        return self.layer_3(self.layer_2(self.layer_1(x)))
    
# instantiate Model
model_1 =  PracticeModel()
model_1

PracticeModel(
  (layer_1): Linear(in_features=1, out_features=10, bias=True)
  (layer_2): Linear(in_features=10, out_features=10, bias=True)
  (layer_3): Linear(in_features=10, out_features=1, bias=True)
)

### Model Training

In [5]:
optimizer =  torch.optim.SGD(params= model_1.parameters(),
                             lr = 0.1)

loss_fn  = nn.BCEWithLogitsLoss()

def accuracy_fn(y_true, y_preds):
    correct = torch.eq(y_true, y_preds).sum().item()
    acc = (correct/len(y_preds)) * 100
    return acc

In [1]:
epochs = 100

for epoch in range(epochs):
    model_1.train()

    y_logits = model_1(X_train)
    y_prob = torch.sigmoid(y_logits)
    acc = accuracy_fn(y_true = y_train,
                      y_preds = y_prob)

    loss = loss_fn(y_logits, 
                   y_train) 
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Testing
    model_1.eval()

    with torch.inference_mode():
        test_logits = model_1(X_test)
        test_prop = torch.sigmoid(test_logits)

        test_loss = loss_fn(test_prop, y_test)
        test_accuracy = accuracy_fn(y_true = y_test,
                                    y_preds = test_prop)
    
        
        if epoch % 10 == 0:
            print(f"Epoch is {epoch} | Training loss = {loss:.2f} | Training accuracy = {acc} | Test accuracy = {test_accuracy}")


NameError: name 'model_1' is not defined

In [22]:
X_test, test_prop

(tensor([[0.8000],
         [0.8200],
         [0.8400],
         [0.8600],
         [0.8800],
         [0.9000],
         [0.9200],
         [0.9400],
         [0.9600],
         [0.9800]]),
 tensor([[0.8305],
         [0.8390],
         [0.8471],
         [0.8549],
         [0.8623],
         [0.8695],
         [0.8763],
         [0.8828],
         [0.8890],
         [0.8949]]))