 ### Reproducibility In PyTorch (trying to make random out of random)

How a neural network is:

` Start with random numbers --> tensor operations --> Update random numbers to make them represent the data best --> Repeat...`

To reduce the randomness in neural networks and PyTorch comes the concept of **random seeds**. For PyTorch it is `torch.manual_seed(Random_Seed)`

Essentially, what the random seed does is flavour the randomness

In [ ]:
import torch 

rand_tensorA =  torch.rand (3, 4)
rand_tensorB =  torch.rand (3, 4)

print(rand_tensorA)
print(rand_tensorB)

print(rand_tensorA == rand_tensorB) 

In [5]:
# Reproducible random tensors
import torch 

# Set random seed
RANDOM_SEED = 42        # could be any integer ...42 is only a standard practice 
torch.manual_seed(RANDOM_SEED) 
rand_tensorC = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) 
rand_tensorD = torch.rand(3, 4)

print(rand_tensorC)
print(rand_tensorD)

print(rand_tensorC == rand_tensorD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors amd pytorch objects on the GPUs (and making faster computations)

GPUs = Faster computation on numbers

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### Check for GPU access with pytorch

In [9]:
import torch
torch.cuda.is_available()

False

In [ ]:


# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else "cpu"
device 

'cpu'

In [ ]:
# count number of devices
torch.cuda.device_count()

1

### Putting Tensors and models on the GPU

The reason for putting on a GPU is because they result in faster computations

In [15]:
# Create a Tensor, default is created on the cpu

tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [18]:
# Move tensors to Gpu (if available)

tensor_on_gpu = tensor.to(device)

tensor_on_gpu

tensor([1, 2, 3])

### Moving tensors back to the cpu  

Last Checkout time ----> 4:08:56