In [1]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Setup device-agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cpu


## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using torch.Tensor() 

In [3]:
scalar =  torch.tensor(7)
scalar 

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item() 


7

In [6]:
# Vector 
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim


1

In [8]:
vector.shape

torch.Size([2])

In [9]:
 # Matrix
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 6, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 6, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 6, 9]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers.`


In [17]:
# Create a random tensor of size (3, 4)
random_tensor =  torch.rand(3, 4)
random_tensor


tensor([[0.8252, 0.0222, 0.3465, 0.5197],
        [0.3609, 0.3083, 0.0644, 0.0896],
        [0.5588, 0.3711, 0.5269, 0.9563]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #colour channels (R, G, B), height, Width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [20]:
# Create a tensor of all zeros
zeros =  torch.zeros(size=(3, 4))
zeros 

test_zero =  random_tensor * zeros 
print(f"Test zero is {test_zero}")
test_zero.shape

Test zero is tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


torch.Size([3, 4])

In [21]:
# Create a tensor of all ones
ones =  torch.ones(size=(3, 4))
ones 

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype


torch.float32

### Creating a range of tensors and tensors-like 

In [23]:
one_to_ten = torch.arange(start=0, end=10000, step=50)
one_to_ten


tensor([   0,   50,  100,  150,  200,  250,  300,  350,  400,  450,  500,  550,
         600,  650,  700,  750,  800,  850,  900,  950, 1000, 1050, 1100, 1150,
        1200, 1250, 1300, 1350, 1400, 1450, 1500, 1550, 1600, 1650, 1700, 1750,
        1800, 1850, 1900, 1950, 2000, 2050, 2100, 2150, 2200, 2250, 2300, 2350,
        2400, 2450, 2500, 2550, 2600, 2650, 2700, 2750, 2800, 2850, 2900, 2950,
        3000, 3050, 3100, 3150, 3200, 3250, 3300, 3350, 3400, 3450, 3500, 3550,
        3600, 3650, 3700, 3750, 3800, 3850, 3900, 3950, 4000, 4050, 4100, 4150,
        4200, 4250, 4300, 4350, 4400, 4450, 4500, 4550, 4600, 4650, 4700, 4750,
        4800, 4850, 4900, 4950, 5000, 5050, 5100, 5150, 5200, 5250, 5300, 5350,
        5400, 5450, 5500, 5550, 5600, 5650, 5700, 5750, 5800, 5850, 5900, 5950,
        6000, 6050, 6100, 6150, 6200, 6250, 6300, 6350, 6400, 6450, 6500, 6550,
        6600, 6650, 6700, 6750, 6800, 6850, 6900, 6950, 7000, 7050, 7100, 7150,
        7200, 7250, 7300, 7350, 7400, 74

In [24]:
# Creating tensors like 
like_zeros =  torch.zeros_like(input = one_to_ten)
like_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** one of the three big errors we'd be running into with Pytorch and deep learning is datatypes 
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device 

In [25]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype = torch.float64, # what datatype 
                               device = None,   # what datatype is tensor on
                               requires_grad=False)   # whether or not to track gradients with this tensor operations
                               

float_32_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [26]:
float_32_tensor.dtype

torch.float64

In [27]:
float_16_tensor =  float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
torch.cuda.is_available()


False

In [29]:
float_16_tensor * float_32_tensor 

tensor([ 9., 36., 81.], dtype=torch.float64)

In [30]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [31]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

### Getting information from Tensors (tensor attributes)

1. Tensors not right datatype --> to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape  --> to get shape from a tensor, we can use `tensor.shape`
3. Tensors not on the right device --> to get device from a tensor, can use `tensor.device` 


In [32]:
# Create a tensor 
some_tensor = torch.rand(3, 4).type(torch.float64)
some_tensor

tensor([[0.6720, 0.8121, 0.2629, 0.9618],
        [0.7903, 0.0432, 0.1361, 0.8688],
        [0.1903, 0.8926, 0.1402, 0.1006]], dtype=torch.float64)

In [33]:
# Find out detais about some tensors
print(some_tensor)
print(f"Datatype of tensors: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}") 

tensor([[0.6720, 0.8121, 0.2629, 0.9618],
        [0.7903, 0.0432, 0.1361, 0.8688],
        [0.1903, 0.8926, 0.1402, 0.1006]], dtype=torch.float64)
Datatype of tensors: torch.float64
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


 ### Manipulating Tensors (Tensor operations)

Tensor operatons include: 
* Addition 
* Subtraction 
* Multiplication
* Division 
* Matrix Multiplication


In [34]:
 # Addition of tensors
tensors = torch.tensor([1,2,3])
tensors + 4

tensor([5, 6, 7])

In [35]:
# Multiplication of tensors 
tensors * 10


tensor([10, 20, 30])

In [36]:
# division of tensors 
tensors / 10 

tensor([0.1000, 0.2000, 0.3000])

In [37]:
# Using Py torch  built in methods
torch.mul(tensors, 4)

tensor([ 4,  8, 12])

In [38]:
torch.add(tensors, 5)

tensor([6, 7, 8])

### Matrix Multiplication 

Two main ways of performing  matrix multiplication in Machine learning and deep learning is :
1. Element-wise multiplication
2. Matrix Multiplication (dot product)  

matrix multiplicaion must satisfy the following conditions:
1. The inner dimensions must match must strictly be  (n by m) * (m by q)
2. The resulting matrix has the shape of the **outer dimensions**
* (n, m) @ (m, n) --> (n, n)
* (3, 2)  @ (2, 9) --> (3, 9)

In [39]:
matrix_1 = torch.rand(3, 2)
matrix_2 = torch.rand(2, 9)
torch.matmul(matrix_1, matrix_2).shape

torch.Size([3, 9])

In [40]:

# Element wise multiplication 
print(tensors, "*", tensors)
print(f" Equals: {tensors * tensors}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
 Equals: tensor([1, 4, 9])


In [41]:
# Matrix Multplicaion 
torch.matmul(tensors, torch.tensor([[3], [4], [6]]))

tensor([29])

In [42]:
%%time
value = 0
for i in range(len(tensors)):
    value += tensors[i] * tensors[i]
print(value)


tensor(14)
CPU times: user 577 μs, sys: 920 μs, total: 1.5 ms
Wall time: 1.24 ms


In [43]:
%%time 
torch.matmul(tensors, tensors)

CPU times: user 234 μs, sys: 49 μs, total: 283 μs
Wall time: 198 μs


tensor(14)

In [44]:
### one of the most common errors in deep learning: shape errors 

tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_a, tensor_b.T) # same as torch.matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### To fix our tensor shape issues, we can manipulate the shape of one of our tensors using the  **transpose**

a **transpose** switches the axes or dimensions of a given tensor




In [45]:
tensor_b, tensor_b.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [46]:
tensor_b.T, tensor_b.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [47]:
torch.mm(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [48]:
x = torch.rand(3, 5)
y = torch.rand(5, 7)
z = torch.mm(x, y)
z, z.shape 

(tensor([[1.9074, 2.3005, 1.1307, 1.8402, 1.6668, 1.6210, 1.0675],
         [1.2445, 2.0573, 0.8950, 1.3827, 1.3481, 1.4323, 1.0814],
         [0.7531, 1.1105, 0.3594, 0.7860, 0.6268, 0.8854, 0.5553]]),
 torch.Size([3, 7]))

 ### Finding min, max, mean and sum of tensors (tensor aggregation)

In [49]:
# creating a tensor 
x.dtypex = torch.arange(0, 100, 10)
x.dtypex

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
# Find the max
torch.max(x), x.max()

(tensor(0.8528), tensor(0.8528))

In [51]:
# Trying the sum 
torch.sum(x), x.sum()

(tensor(7.5880), tensor(7.5880))

In [52]:
# find the mean ---> The torch.mean(0) method requires a tensor of the dtype of float32 datatype to work 
torch.mean(x.type(torch.float32))


tensor(0.5059)

### Finding the positional max and min of vectors

In [53]:
x

tensor([[0.8252, 0.6158, 0.5883, 0.8528, 0.5583],
        [0.5915, 0.7754, 0.3314, 0.2785, 0.8234],
        [0.0295, 0.3342, 0.1502, 0.5028, 0.3308]])

In [54]:
# The argmin helps find the tensor with the minimum value and returns index postion 
x.argmin()

tensor(10)

In [55]:
# argmax returns the maximum value's position
x.argmax()

tensor(3)

### Reshaping, Stacking, Squeezing and Unsqueezing tensors.

* Reshaping - reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor 
* Stacking -  combines multiple tensors on top of each others
* Squeeze - removes all '1' dimensions from a tensor 
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions swapped(permuted) in a certain way 

In [56]:
# Reshaping 
import torch
x =  torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [57]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [59]:
# Change view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stack =  torch.stack([x,x,x,x], dim=1)
x_stack

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_hstack = torch.hstack((x,x, x, x, x, x))
x_hstack, x_hstack.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([54]))

In [ ]:
x_vstack = torch.vstack((x, x, x, x, x, x))
x_vstack, x_vstack.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([6, 9]))

In [ ]:
# Torch.squeeze() -removes all single dimensions from a target tensor 
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
 #torch.unsqueeze() - adds a single dimension to atarget tensor at a specific dim 
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed =  x_squeezed.unsqueeze(dim=0)
print(f"x_unsqueeze: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
x_unsqueeze: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
#torch.permute() rearrange the  dimensions of a target tensor in a specified order 
x_original = torch.rand(size=(224, 224, 3)) # (height, width, color_channels)

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0->1, 1->2, 2-> 0
print(f"Previous Shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, heights, width]

Previous Shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0]

tensor(0.9921)

### indexing (selecting data from tensors)

indexing with pytorch is similar to indexing with NumPy

In [ ]:
# Create a tensor 
import torch 
x =  torch.arange(1, 10).reshape(1,3, 3)
x, x.shape 

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
# indexing on the last dimension 
x[0,0,0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

a ":" can be used to select all of a target dimension 

In [ ]:
x[:, 0:2, 1]

tensor([[2, 5]])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
x[0, 2, -1]

tensor(9)

In [ ]:
x[:, :, -1]

tensor([[3, 6, 9]])

## PyTorch  Tensors and NumPy

Numpy is a popular scientific python numerical computing library.
This gives PyTorch the functionalities to interact with it.
* Converting data from NumPy to PyTorch we make use of `torch.from_numpy(ndarray)` 
* Converting data from PyTorch to Numpy we make use of `torch.Tensor.numpy()`


In [60]:
#Numpy array to tensor
import torch 
import numpy as np 

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor 

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [63]:
tensor.dtype

# When converting from numpy to pytorch, float64 is the datatype used.
# PyTorch standard datatype is float32
# if pytorch must remain as a float32 then `.type(torch.float32)`

torch.float64

In [64]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:

# From Tensor to numpy  
tensor = torch.ones(7)
num_tensor = tensor.numpy() 
tensor, num_tensor 

In [ ]:
# Changing the tensor 
tensor += 1
tensor, num_tensor  

(tensor([8., 8., 8., 8., 8., 8., 8.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))