In [2]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using torch.Tensor() 

In [3]:
scalar =  torch.tensor(7)
scalar 

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item() 


7

In [6]:
# Vector 
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim


1

In [8]:
vector.shape

torch.Size([2])

In [9]:
 # Matrix
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 6, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 6, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1