In [ ]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using torch.Tensor() 

In [ ]:
scalar =  torch.tensor(7)
scalar 

In [ ]:
scalar.ndim

In [ ]:
# Get tensor back as Python int
scalar.item() 


In [ ]:
# Vector 
vector = torch.tensor([7, 7])
vector

In [ ]:
vector.ndim


In [ ]:
vector.shape

In [ ]:
 # Matrix
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

In [ ]:
MATRIX.ndim

In [ ]:
MATRIX[1]

In [ ]:
MATRIX.shape

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 6, 9]]])
TENSOR

In [ ]:
TENSOR.ndim

In [ ]:
TENSOR.shape

In [ ]:
TENSOR[0]

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers.`


In [ ]:
# Create a random tensor of size (3, 4)
random_tensor =  torch.rand(3, 4)
random_tensor


In [ ]:
random_tensor.ndim

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #colour channels (R, G, B), height, Width
random_image_size_tensor.shape, random_image_size_tensor.ndim

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros =  torch.zeros(size=(3, 4))
zeros 

test_zero =  random_tensor * zeros 
print(f"Test zero is {test_zero}")
test_zero.shape

In [ ]:
# Create a tensor of all ones
ones =  torch.ones(size=(3, 4))
ones 

In [ ]:
ones.dtype


### Creating a range of tensors and tensors-like 

In [ ]:
one_to_ten = torch.arange(start=0, end=10000, step=50)
one_to_ten


In [ ]:
# Creating tensors like 
like_zeros =  torch.zeros_like(input = one_to_ten)
like_zeros

### Tensor Datatypes

**Note:** one of the three big errors we'd be running into with Pytorch and deep learning is datatypes 
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device 

In [ ]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype = torch.float64, # what datatype 
                               device = None,   # what datatype is tensor on
                               requires_grad=False)   # whether or not to track gradients with this tensor operations
                               

float_32_tensor

In [ ]:
float_32_tensor.dtype

In [ ]:
float_16_tensor =  float_32_tensor.type(torch.float16)
float_16_tensor

In [ ]:
torch.cuda.is_available()


In [ ]:
float_16_tensor * float_32_tensor 

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

In [ ]:
float_32_tensor * int_32_tensor

### Getting information from Tensors (tensor attributes)

1. Tensors not right datatype --> to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape  --> to get shape from a tensor, we can use `tensor.shape`
3. Tensors not on the right device --> to get device from a tensor, can use `tensor.device` 


In [ ]:
# Create a tensor 
some_tensor = torch.rand(3, 4).type(torch.float64)
some_tensor

In [ ]:
# Find out detais about some tensors
print(some_tensor)
print(f"Datatype of tensors: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

 ### Manipulating Tensors (Tensor operations)

Tensor operatons include: 
* Addition 
* Subtraction 
* Multiplication
* Division 
* Matrix 

In [ ]:
 # Addition of tensors
tensors = torch.tensor([1,2,3])
tensors + 4

In [ ]:
# Multiplication of tensors 
tensors * 10


In [ ]:
# division of tensors 
tensors / 10 

In [ ]:
# Using Py torch  built in methods
torch.mul(tensors, 4)

In [ ]:
torch.add(tensors, 5)

### Matrix Multiplication 

Two main ways of performing  matrix multiplication in  deep learning and deep learning is :
1. Element-wise multiplication
2. Matrix Multiplication (dot product)  

matrix muktiplicaion must satisfy the following conditions:
1. The inner dimensions must match must strictly be  (n by m) * (m by q)
2. The resulting matrix has the shape of the **outer dimensions**
* (n, m) @ (m, n) --> (n, n)
* (3, 2)  @ (2, 9) --> (3, 3)

In [ ]:

# Element wise multiplication 
print(tensors, "*", tensors)
print(f" Equals: {tensors * tensors}")

In [ ]:
# Matrix Multplicaion 
torch.matmul(tensors, torch.tensor([[3], [4], [6]]))

In [ ]:
%%time
value = 0
for i in range(len(tensors)):
    value += tensors[i] * tensors[i]
print(value)


In [ ]:
%%time 
torch.matmul(tensors, tensors)

In [177]:
### one of the most common errors in deep learning: shape errors 

tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_a, tensor_b.T) # same as torch.matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### To fix our tensor shape issues, we can manipulate the shape of one of our tensors using the  **transpose**

a **transpose** switches the axes or dimensions of a given tensor




In [ ]:
tensor_b, tensor_b.shape

In [ ]:
tensor_b.T, tensor_b.T.shape

In [178]:
torch.mm(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [179]:
x = torch.rand(3, 5)
y = torch.rand(5, 7)
z = torch.mm(x, y)
z, z.shape 

(tensor([[1.1909, 1.4664, 1.4502, 1.7535, 1.8859, 1.7150, 1.3354],
         [0.9220, 1.1604, 1.2396, 1.9512, 1.9164, 1.4682, 1.5962],
         [0.8329, 1.4315, 1.5455, 1.5414, 1.5323, 1.3109, 1.1382]]),
 torch.Size([3, 7]))

 ### Finding min, max, mean and sum of tensors (tensor aggregation)

In [180]:
# creating a tensor 
x = torch.arange(0, 100, 10)
x.dtype

torch.int64

In [181]:
# Find the min 
torch.min(x), x.min()


(tensor(0), tensor(0))

In [182]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [183]:
# Trying the sum 
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [184]:
# find the mean ---> The torch.mean(0) method requires a tensor of the dtype of float32 datatype to work 
torch.mean(x.type(torch.float32))


tensor(45.)

### Finding the positional max and min of vectors

In [185]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [188]:
# The argmin helps find the tensor with the minimum value and returns index postion 
x.argmin()

tensor(0)

In [191]:
# argmax returns the maximum value's position
x.argmax()

tensor(9)

### Reshaping, Stacking, Squeezing and Unsqueezing tensors.

* Reshaping - reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor 
* Stacking -  combines multiple tensors on top of each others
* Squeeze - removes all '1' dimensions from a tensor 
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions swapped(permuted) in a certain way 

In [ ]:
# Reshaping 
import torch
x =  torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [6]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [9]:
# Change view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [18]:
# Stack tensors on top of each other
x_stack =  torch.stack([x,x,x,x], dim=1)
x_stack

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [26]:
x_hstack = torch.hstack((x,x, x, x, x, x))
x_hstack, x_hstack.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([54]))

In [25]:
x_vstack = torch.vstack((x, x, x, x, x, x))
x_vstack, x_vstack.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([6, 9]))