In [18]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using torch.Tensor() 

In [19]:
scalar =  torch.tensor(7)
scalar 

tensor(7)

In [20]:
scalar.ndim

0

In [21]:
# Get tensor back as Python int
scalar.item() 


7

In [22]:
# Vector 
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [23]:
vector.ndim


1

In [24]:
vector.shape

torch.Size([2])

In [25]:
 # Matrix
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [26]:
MATRIX.ndim

2

In [27]:
MATRIX[1]

tensor([ 9, 10])

In [28]:
MATRIX.shape

torch.Size([2, 2])

In [29]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 6, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 6, 9]]])

In [30]:
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([1, 3, 3])

In [33]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 6, 9]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers.`


In [ ]:
# Create a random tensor of size (3, 4)
random_tensor =  torch.rand(3, 4)
random_tensor


In [48]:
random_tensor.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #colour channels (R, G, B), height, Width
random_image_size_tensor.shape, random_image_size_tensor.ndim

torch.Size([10, 3, 4])