In [1]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using torch.Tensor() 

In [2]:
scalar =  torch.tensor(7)
scalar 

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item() 


7

In [5]:
# Vector 
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim


1

In [7]:
vector.shape

torch.Size([2])

In [8]:
 # Matrix
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 6, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 6, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 6, 9]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers.`


In [16]:
# Create a random tensor of size (3, 4)
random_tensor =  torch.rand(3, 4)
random_tensor


tensor([[0.5244, 0.9217, 0.8791, 0.2842],
        [0.5783, 0.2505, 0.6736, 0.1350],
        [0.6452, 0.6272, 0.5017, 0.5662]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #colour channels (R, G, B), height, Width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [19]:
# Create a tensor of all zeros
zeros =  torch.zeros(size=(3, 4))
zeros 

test_zero =  random_tensor * zeros 
print(f"Test zero is {test_zero}")
test_zero.shape

Test zero is tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


torch.Size([3, 4])

In [20]:
# Create a tensor of all ones
ones =  torch.ones(size=(3, 4))
ones 

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype


torch.float32

### Creating a range of tensors and tensors-like 

In [22]:
one_to_ten = torch.arange(start=0, end=10000, step=50)
one_to_ten


tensor([   0,   50,  100,  150,  200,  250,  300,  350,  400,  450,  500,  550,
         600,  650,  700,  750,  800,  850,  900,  950, 1000, 1050, 1100, 1150,
        1200, 1250, 1300, 1350, 1400, 1450, 1500, 1550, 1600, 1650, 1700, 1750,
        1800, 1850, 1900, 1950, 2000, 2050, 2100, 2150, 2200, 2250, 2300, 2350,
        2400, 2450, 2500, 2550, 2600, 2650, 2700, 2750, 2800, 2850, 2900, 2950,
        3000, 3050, 3100, 3150, 3200, 3250, 3300, 3350, 3400, 3450, 3500, 3550,
        3600, 3650, 3700, 3750, 3800, 3850, 3900, 3950, 4000, 4050, 4100, 4150,
        4200, 4250, 4300, 4350, 4400, 4450, 4500, 4550, 4600, 4650, 4700, 4750,
        4800, 4850, 4900, 4950, 5000, 5050, 5100, 5150, 5200, 5250, 5300, 5350,
        5400, 5450, 5500, 5550, 5600, 5650, 5700, 5750, 5800, 5850, 5900, 5950,
        6000, 6050, 6100, 6150, 6200, 6250, 6300, 6350, 6400, 6450, 6500, 6550,
        6600, 6650, 6700, 6750, 6800, 6850, 6900, 6950, 7000, 7050, 7100, 7150,
        7200, 7250, 7300, 7350, 7400, 74

In [23]:
# Creating tensors like 
like_zeros =  torch.zeros_like(input = one_to_ten)
like_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** one of the three big errors we'd be running into with Pytorch and deep learning is datatypes 
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device 

In [24]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype = torch.float64, # what datatype 
                               device = None,   # what datatype is tensor on
                               requires_grad=False)   # whether or not to track gradients with this tensor operations
                               

float_32_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [25]:
float_32_tensor.dtype

torch.float64

In [26]:
float_16_tensor =  float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
torch.cuda.is_available()


False

In [28]:
float_16_tensor * float_32_tensor 

tensor([ 9., 36., 81.], dtype=torch.float64)

In [29]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [30]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

### Getting information from Tensors (tensor attributes)

1. Tensors not right datatype --> to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape  --> to get shape from a tensor, we can use `tensor.shape`
3. Tensors not on the right device --> to get device from a tensor, can use `tensor.device` 


In [31]:
# Create a tensor 
some_tensor = torch.rand(3, 4).type(torch.float64)
some_tensor

tensor([[0.5361, 0.0857, 0.8717, 0.4340],
        [0.3920, 0.9037, 0.8322, 0.0842],
        [0.3774, 0.8484, 0.0892, 0.9841]], dtype=torch.float64)

In [32]:
# Find out detais about some tensors
print(some_tensor)
print(f"Datatype of tensors: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5361, 0.0857, 0.8717, 0.4340],
        [0.3920, 0.9037, 0.8322, 0.0842],
        [0.3774, 0.8484, 0.0892, 0.9841]], dtype=torch.float64)
Datatype of tensors: torch.float64
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


 ### Manipulating Tensors (Tensor operations)

Tensor operatons include: 
* Addition 
* Subtraction 
* Multiplication
* Division 
* Matrix 

In [33]:
 # Addition of tensors
tensors = torch.tensor([1,2,3])
tensors + 4

tensor([5, 6, 7])

In [34]:
# Multiplication of tensors 
tensors * 10


tensor([10, 20, 30])

In [35]:
# division of tensors 
tensors / 10 

tensor([0.1000, 0.2000, 0.3000])

In [36]:
# Using Py torch  built in methods
torch.mul(tensors, 4)

tensor([ 4,  8, 12])

In [37]:
torch.add(tensors, 5)

tensor([6, 7, 8])

### Matrix Multiplication 

Two main ways of performing  matrix multiplication in  deep learning and deep learning is :
1. Element-wise multiplication
2. Matrix Multiplication (dot product)  

matrix muktiplicaion must satisfy the following conditions:
1. The inner dimensions must match must strictly be  (n by m) * (m by q)
2. The resulting matrix has the shape of the **outer dimensions**
* (n, m) @ (m, n) --> (n, n)
* (3, 2)  @ (2, 9) --> (3, 3)

In [38]:

# Element wise multiplication 
print(tensors, "*", tensors)
print(f" Equals: {tensors * tensors}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
 Equals: tensor([1, 4, 9])


In [39]:
# Matrix Multplicaion 
torch.matmul(tensors, torch.tensor([[3], [4], [6]]))

tensor([29])

In [40]:
%%time
value = 0
for i in range(len(tensors)):
    value += tensors[i] * tensors[i]
print(value)


tensor(14)
CPU times: user 874 μs, sys: 0 ns, total: 874 μs
Wall time: 1.06 ms


In [41]:
%%time 
torch.matmul(tensors, tensors)

CPU times: user 694 μs, sys: 0 ns, total: 694 μs
Wall time: 2.88 ms


tensor(14)

In [42]:
### one of the most common errors in deep learning: shape errors 

tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_a, tensor_b) # same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### To fix our tensor shape issues, we can manipulate the shape of one of our tensors using the  **transpose**

a **transpose** switches the axes or dimensions of a given tensor




In [ ]:
tensor_b, tensor_b.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_b.T, tensor_b.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
x = torch.rand(3, 5)
y = torch.rand(5, 7)
z = torch.mm(x, y)
z, z.shape 

(tensor([[1.4519, 1.3484, 1.1292, 1.6001, 1.5743, 1.8274, 1.2157],
         [1.2012, 0.7714, 0.8284, 1.1029, 1.1928, 1.1159, 0.9880],
         [1.5812, 1.3138, 1.0998, 1.6609, 1.6950, 1.7419, 1.4169]]),
 torch.Size([3, 7]))

 ### Finding min, max, mean and sum of tensors (tensor aggregation)

In [ ]:
# creating a tensor 
x = torch.arange(0, 100, 10)
x.dtype

torch.int64

In [ ]:
# Find the min 
torch.min(x), x.min()


(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Trying the sum 
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
# find the mean ---> The torch.mean(0) method requires a tensor of the dtype of float32 datatype to work 
torch.mean(x.type(torch.float32)) 

tensor(45.)

### Finding the positional max and min of functions 