In [2]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using torch.Tensor() 

In [3]:
scalar =  torch.tensor(7)
scalar 

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item() 


7

In [6]:
# Vector 
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim


1

In [8]:
vector.shape

torch.Size([2])

In [9]:
 # Matrix
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[1, 2, 3], 
                       [6, 5, 9],
                       [2, 4, 5]])
TENSOR  

tensor([[1, 2, 3],
        [6, 5, 9],
        [2, 4, 5]])

In [16]:
TENSOR.ndim

2