 ### Reproducibility In PyTorch (trying to make random out of random)

How a neural network is:

` Start with random numbers --> tensor operations --> Update random numbers to make them represent the data best --> Repeat...`

To reduce the randomness in neural networks and PyTorch comes the concept of **random seeds**. For PyTorch it is `torch.manual_seed(Random_Seed)`

Essentially, what the random seed does is flavour the randomness

In [2]:
import torch 

rand_tensorA =  torch.rand (3, 4)
rand_tensorB =  torch.rand (3, 4)

print(rand_tensorA)
print(rand_tensorB)

print(rand_tensorA == rand_tensorB) 

tensor([[0.8505, 0.5489, 0.1134, 0.5843],
        [0.3768, 0.3797, 0.6477, 0.6077],
        [0.1130, 0.7222, 0.4375, 0.9427]])
tensor([[0.7033, 0.8100, 0.0225, 0.8829],
        [0.2677, 0.3633, 0.1056, 0.4086],
        [0.8896, 0.4855, 0.4293, 0.2723]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [3]:
# Reproducible random tensors
import torch 

# Set random seed
RANDOM_SEED = 42        # could be any integer ...42 is only a standard practice 
torch.manual_seed(RANDOM_SEED) 
rand_tensorC = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) 
rand_tensorD = torch.rand(3, 4)

print(rand_tensorC)
print(rand_tensorD)

print(rand_tensorC == rand_tensorD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors amd pytorch objects on the GPUs (and making faster computations)

GPUs = Faster computation on numbers

In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### Check for GPU access with pytorch

In [5]:
import torch
torch.cuda.is_available()

False

In [6]:


# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else "cpu"
device 

'cpu'

In [7]:
# count number of devices
torch.cuda.device_count()

0

### Putting Tensors and models on the GPU

The reason for putting on a GPU is because they result in faster computations

In [8]:
# Create a Tensor, default is created on the cpu

tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [9]:
# Move tensors to Gpu (if available)

tensor_on_gpu = tensor.to(device)

tensor_on_gpu

tensor([1, 2, 3])

### Moving tensors back to the cpu  

In [ ]:
tensor_on_gpu.numpy() 

""" This worked on this laptop because the cause tensor_on_gpu was
    initialised to tensor.to(device) and the device was set 
    to cpu in the absence of a GPU."""



array([1, 2, 3])

In [11]:
tensor_on_gpu

tensor([1, 2, 3])

Last Checkout time ----> 4:08:56